# IMAP - ACME CHALLENGE

server {
    listen 80;
    server_name imap.enoblega.com.ar;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 404;
    }
}


# SMTP - ACME CHALLENGE

server {
    listen 80;
    server_name smtp.enoblega.com.ar;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 404;
    }
}