# CV PAGE

server {
    listen 80;
    server_name cv.enoblega.com.ar;

    limit_req zone=global burst=10 nodelay;
    limit_conn conn_limit 20;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {

        location ~* /\.(env|git|htaccess)$ {
            return 444;
        }

        location ~* /(wp-admin|wp-login|xmlrpc.php)$ {
            return 444;
        }

        location ~* /(boaform|actuator|cgi-bin|vendor)$ {
            return 444;
        }

        location ~* \.(sql|bak|old|zip)$ {
            return 444;
        }

        proxy_pass http://prueba2-ngx;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}


# CV PAGE HTTPS

server {
    listen 443 ssl;
    server_name cv.enoblega.com.ar;

    limit_req zone=global burst=10 nodelay;
    limit_conn conn_limit 20;

    ssl_certificate /etc/letsencrypt/live/cv.enoblega.com.ar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cv.enoblega.com.ar/privkey.pem;

    location / {

        proxy_pass http://prueba2-ngx;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}