server {
    listen 443 ssl;
    server_name cv.enoblega.com.ar;

    limit_req zone=global burst=10 nodelay;
    limit_conn conn_limit 20;

    ssl_certificate /etc/letsencrypt/live/cv.enoblega.com.ar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cv.enoblega.com.ar/privkey.pem;

    root /var/www/sites/cv;
    index index.html;

    location ~* /\.(env|git|htaccess)$ {
        return 444;
    }

    location ~* /(wp-admin|wp-login|xmlrpc.php)$ {
        return 444;
    }

    location ~* /(boaform|actuator|cgi-bin|vendor)$ {
        return 444;
    }

    location ~* \.(sql|bak|old|zip)$ {
        return 444;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}