# TEST / DOCKER PAGE

server {
    listen 80;
    server_name docker.enoblega.com.ar;

    limit_req zone=global burst=10 nodelay;
    limit_conn conn_limit 20;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://prueba1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}