# LAB LANDING PAGE

server {
    listen 80;
    server_name lab.enoblega.com.ar;

    limit_req zone=global burst=10 nodelay;
    limit_conn conn_limit 20;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}


# LAB LANDING PAGE HTTPS
server {
    listen 443 ssl;
    server_name lab.enoblega.com.ar;

    limit_req zone=global burst=10 nodelay;
    limit_conn conn_limit 20;

    ssl_certificate /etc/letsencrypt/live/lab.enoblega.com.ar/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lab.enoblega.com.ar/privkey.pem;

    root /var/www/sites/lab;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}