# ENOBLEGA.COM.AR — LANDING (v2)

# HTTP: ACME challenge + redirect a HTTPS
server {
    listen 80;
    server_name enoblega.com.ar www.enoblega.com.ar;

    limit_req zone=global burst=10 nodelay;
    limit_conn conn_limit 20;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}


# # ENOBLEGA.COM.AR — LANDING (v2) HTTPS
# server {
#     listen 443 ssl;
#     server_name enoblega.com.ar www.enoblega.com.ar;

#     limit_req zone=global burst=10 nodelay;
#     limit_conn conn_limit 20;

#     ssl_certificate /etc/letsencrypt/live/enoblega.com.ar/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/enoblega.com.ar/privkey.pem;

#     root /var/www/sites/enoblegav2;
#     index index.html;

#     location ~* /\.(env|git|htaccess)$ {
#         return 444;
#     }

#     location ~* /(wp-admin|wp-login|xmlrpc.php)$ {
#         return 444;
#     }

#     location ~* /(boaform|actuator|cgi-bin|vendor)$ {
#         return 444;
#     }

#     location ~* \.(sql|bak|old|zip)$ {
#         return 444;
#     }

#     location / {
#         try_files $uri $uri/ =404;
#     }
# }
