events {}

http {
    server_tokens off;

    # Hardening NGINX
    client_body_timeout 10s;
    client_header_timeout 10s;
    keepalive_timeout 15s;
    send_timeout 10s;

    client_max_body_size 1M;

    ignore_invalid_headers on;
    reset_timedout_connection on;

    # RATE LIMIT
    limit_req_zone $binary_remote_addr zone=global:10m rate=5r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Virtual Hosts
    include /etc/nginx/sites/*.conf;

    include /etc/nginx/mime.types;
}